### ISSUE TITLE
An error occurred during compilation

### ISSUE THREAD

**Issue by 377079200** [BioPP/testnh#3]
Hello, 
this program is very useful to me, but when I installed the latest version v3.0.0, there were a lot of compilation problems. Can you provide a new version of the compiled program?

`-- Found /bin/gzip compression program, using file extension .gz
-- bpp-core3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /home/renxf/FXQ-publicWGS/test/lib/libbpp-core3.so.1.0.0
--   includes: /home/renxf/FXQ-publicWGS/test/include
-- bpp-seq3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /home/renxf/FXQ-publicWGS/test/lib/libbpp-seq3.so.1.0.0
--   includes: /home/renxf/FXQ-publicWGS/test/include
-- bpp-phyl3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /home/renxf/FXQ-publicWGS/test/lib/libbpp-phyl3.so.1.0.0
--   includes: /home/renxf/FXQ-publicWGS/test/include
-- bpp-popgen3 1.0.0 found:
--   static lib: not built/installed
--   shared lib: /home/renxf/FXQ-publicWGS/test/lib/libbpp-popgen3.so.1.0.0
--   includes: /home/renxf/FXQ-publicWGS/test/include
-- makeinfo program not found: 'info' and 'html' target disabled (builds info/html doc)
-- Configuring done
CMake Error at CMakeLists.txt:121 (ADD_DEPENDENCIES):
  The dependency target "info" of target "rpm" does not exist.
`

**Comment by lgueguen** [comment]
Hello,

this is fixed, you should be able to compile now.

Cheers,
Laurent
