### ISSUE TITLE
TestNH configuration error

### ISSUE THREAD

**Issue by ajhsdk** [BioPP/testnh#4]
Recently I have troble installing TestNH on CentOS. As you know, the programs depends on the Bio++ libraries. First, I try TestNH v3.0.0 (2021) with  BIo++ v3.0.0,  it comes with this error: "Could not find a package configuration file provided by "bpp-phyl" (requested version 12.0.0) with any of the following names." 

     So I turn to Bio++ v2.4.1(with bpp-phyl v12.0.0), but unfortunately, new error occurs: "fatal error: Bpp/Phyl/Mapping/PhyloMappings/OneProcessSequenceSubstitutionMapping.h: No such file or directory #include<Bpp/Phyl/Mapping/PhyloMappings/OneProcessSequenceSubstitutionMapping.h>."I have also tried to manually configuring the missing files, these file errors are solved, but new error occurs. I suspect this is because their versions are incompatible.

     Finally, I try TestNH v2.3.2 with Bio++2.3.2. Fortunately, the configuration worked and I was able to call MapNH successfully, but I got an error when I submitted a task to perform substitution mapping, even with your example data and code. This is the error: "/ds3200_1/users_root/wuyou/.lsbatch/1672992832.999921.shell: line 30: 2303887 Segmentation fault (core dumped) "

**Comment by lgueguen** [comment]
Hello,

you should upgrade all bpp libraries & programs to version 3.

Cheers,
Laurent

**Comment by ajhsdk** [comment]
>

**Comment by ajhsdk** [comment]
I really appreciate your help, I have installed testNH version3 successfully. But when I run the example data with example code, new error occurs:" Parsing options:
Parsing file MapNH2.bpp for options.
Random seed set to.....................: 5489
Alphabet type .........................: Codon(letter=DNA)
Genetic Code...........................: VertebrateMitochondrial
Missing data input.sequence.file option
	from  bpp::BppSequenceApplication::getConstAlignmentsMap
	from  mapnh(main+0x2f7) [0x423e17] "

**Comment by lgueguen** [comment]
It means that you did not provide an alignment file name to mapnh.

Actually, the syntax of config file between v2 & v3 as changed at some point, so perhaps you should update it. Send it to me and I do it.

Cheers,
Laurent

**Comment by ajhsdk** [comment]
Yes, I think it's because configuration file problem. But I'm sorry, I don't know much about C++, so I don't konw which file to send you. If any bother, I ask for your generous forgiveness.

**Comment by lgueguen** [comment]
It is not linked to C++, it is only about usage config file. When you command:

mapnh param=toto.bpp

I think your config file toto.bpp is out of date. You can send it to me so that I check/fix it.

Cheers,
Laurent
