### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by EricDeveaud** [BioPP/testnh#7]
Hello,

you should upgrade all bpp libraries & programs to version 3.

Cheers,
Laurent

_Originally posted by @lgueguen in https://github.com/BioPP/testnh/issues/4#issuecomment-1374397188_

**Comment by EricDeveaud** [comment]
while looking at Bio++ repos for bpp-core, seq, phyl, etc... 
all release are tagged 2.4.1

where can we found version3 of BioPP components ?
some tagged version (eg bpp-phyl) are away from near to 1400 commits.

maybee it will worth to tagg new version 3 releases

regards

Eric

**Comment by jydu** [comment]
Hi Eric,

Version 3 is not released yet, you can get the current version by pulling the master branch. Aside ongoing minor tweaks, it is relatively stable.

Julien.

**Comment by EricDeveaud** [comment]
that what I thoought.

as said before maybee it will be helpfull to tag new releases 
and maybee provide a one repo that holds all the bpplibs 

tagging new version will help to package testnh and bppsuite that rely on version 3 

regards

Eric

**Comment by jydu** [comment]
Hi,

New releases are tagged, which triggers the build of official packages (e.g. debian). Version 3 is just not released yet. As it underwent a major rewriting of many core classes and functions, most of the code had to be ported. While this can now be considered done, we are still in the process of updating dependent programs and the documentation.

Cheers,

Julien.

**Comment by EricDeveaud** [comment]
thanks for the explanation.
